### ISSUE TITLE
Listener "take" with filters

### ISSUE THREAD

**Issue by guillaumecrespel** [alakarteio/k-simple-state#26]
add filters to take helpers

```es6
take( ...matches )( ...filters )( reaction )
```
Test to execute action : (matches1 OR matches2) AND (filter1 AND filter2)

OR

```es6
take( ...filters )( ...matches )( reaction )
const takeNoFilter = take()( ...matches )( reaction )
takeNoFilter( ...matches )( reaction )
```

**Comment by fabienjuif** [comment]
The base discussion is about the API.
 - Is `take` a good name ? (if not, feel free to open an other issue)

 - How do we mix `or` and `and` ?
   * `take([filter1, orFilter2])(andFilter3)(reaction)`
   * `take([filter1, orFilter2], andFilter3)(reaction)`
 
 - It has to be clean when there is not `and` filters
   * `take([filter1, orFilter2])(/* no 'and' filter */)(reaction)`: seems ugly
   * `take([filter1, orFilter2])(reaction)`: seems fine

Overall, I think `matches` and `filters` are same concerns: **filter the action to react**. In both signature you can pass `function`, it means you can filter on payload, or whatever if you want to.

We can even pass the store to access `getState` (or specifics reducer `get`) if you want to.

**Comment by guillaumecrespel** [comment]
for me, the `matches` should be just one or more regexp to filter action name. So filters is here to test the payload value.

**Comment by fabienjuif** [comment]
As I said, you can **already** pass a function to take: 
```js
take(action => action.payload.includes('ok'), (action) => { console.log(action.type) })
```

Maybe we should work on composition functions:
```js
import { take, and, or } from 'k-simple-state' 
take(and(or(filter1, filter2), filter3)))(reaction)
```
?

**Comment by guillaumecrespel** [comment]
or chainage ? 
```es6
take(filter1, filter2).or(filter3, filter4)(reaction)
```
it's a AND between filter1 and filter2, and between filter3 and 4

**Comment by fabienjuif** [comment]
Yes maybe.
If the code is still maintainable behind that :)

**Comment by fabienjuif** [comment]
Ok, @bpetetot / @guillaumecrespel .

Just right now I wrote this with `k-mst-onaction`: 
![image](https://user-images.githubusercontent.com/17828231/35276939-66e1304e-0045-11e8-88e3-797099c25730.png)

I feel like this is more simple to understand and better to write/read a **OR**.

So I think we should not write the array version of take. And push this to make **OR**.
And then we could use multiparams as a **AND*.

```js
take(filter1, andFilter3)(reaction)
take(orFilter2, andFilter3)(reaction)
```

What do you think ?

**Comment by guillaumecrespel** [comment]
ok, so with your exemple, reaction is execute only if `filter1` **AND** `andFilter3`. why not **OR** ?

**Comment by fabienjuif** [comment]
be cause the **OR** is written withe the second line.

```js
take(filter1, andFilter3)(reaction) // case 1
take(orFilter2, andFilter3)(reaction) // or case 2
take(orFilter4)(reaction) // or case 3
```

**Comment by EmrysMyrddin** [comment]
So if I understand you, a common patern will be to have a first parameter to filter on the path and a second one to filter based on arguments :
```es6
take('/action/full/path/', ({ args: [x, y] }) => x !== '' && y > 0)((action, tree) => {
  // do some reaction
})
```

**Comment by EmrysMyrddin** [comment]
Perhaps it can be usefull to flip the take curried arguments :
```es6
const reaction = take((action, tree) => /* do something */)
reaction(filter1)
reaction(orfilter2, andFilter3)
reaction(orfilter4)
```

Or to keep the take as it is, we can add a second function
```es6
const reaction = takeWith((action, tree) => /* do something */)
reaction(filter1)
reaction(orfilter2, andFilter3)
reaction(orfilter4)

**Comment by fabienjuif** [comment]
```js
take('/action/full/path/', ({ args: [x, y] }) => x !== '' && y > 0)((action, tree) => {
  // do some reaction
})
```

This pattern @EmrysMyrddin seems useless to me because we can give `take` a function that take these parameters:
 - action
 - store (we have to add it)

So you can already filter on both action type and action payload if needed.
I can see the benefit of hiding the `type` from the action because 90% of the time we'll filter on it.
I can't see the benefit of hiding the `payload`, in this case use a fonction.

----

For `reaction` we argue about that at Zenika.
I like the idea, but I feel unconfortable with notions around that, take this example, what will be names ?
```
// todos.js
import { takeWith } from 'k-simple-state'
 
export const complete = takeWith(action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
}

// listeners.js
import { complete } from './todos' 

export default [
  // here it seems odd to me to call a fonction 'complete' passing an action type :)
  complete('@@ui_CLICKED_COMPLETE'),
]
```

**Comment by EmrysMyrddin** [comment]
@fabienjuif I don't ask to hide anything :-) I'm just trying to imagine how we can use your suggested API. And it seems pretty good to me.

---

Yes, with this name it feels odd... Perhaps with a better naming convention for this type of reaction ? 
If we can't find a good one, it's not that problematic to pass our reaction to each take.

**Comment by fabienjuif** [comment]
@EmrysMyrddin I know you don't ask to hide anything :)
What I try to say is:
 1.  in `take` approach, we hide `type` when we are doing this: `take('MY_ACTION_TYPE')(reaction)`, this is a fact, and I can agree with that because we will use `type` filter 90% of the time
 2. in @guillaumecrespel proposal to add a `payload` filter: `take('MY_ACTION_TYPE')(payload => payload > 10)(reaction)` we try to hide `action.payload`, and I can't agree with that because this will be use 9% of the time
 3. the remaining 1% is for: `take(action => action.notPayloadNorType > 10)(reaction)`

And I put the **2.** and the **3.** in the same "basket" (panier in french) 

This was not against you ;)


----

Try to get my example and find a name.
It will feel:
 - either odd in the **todos.js** file when you export the reaction
 - either odd in the **listeners.js** file where you use this reaction

I have the **feeling** that if we can't put a name on it, this is not a good pattern :)
So -> let's try to put a name on it if you agree :p

**Comment by EmrysMyrddin** [comment]
@fabienjuif Ok, so we are agree. It's because I was thinking about a polymorphic function that take several types of argument, as k-onaction library.

```es6
take(action => action.payload.x > 0)(reaction
// or
take('ACTION_TYPE')(reaction)
//or
take(\.*REQUEST\)(reaction)
```

And each parameter for take can be of all type. And the action must fullfill all given filters to execute the reaction.

**Comment by fabienjuif** [comment]
Yes `take` is about that.
And this is why I don't agree putting an extra braces just for the payload ;)

**Comment by fabienjuif** [comment]
Ok I think we agree.

### Summary
`take` will be refactored 
 - to be "currified": `take(filter)(reaction)`
 - to accept multiple params as **AND**: `take(filter1, andFilter2)(reaction)`
 - to write **OR** we will use as many `take` as **OR** or use `filter` parameter as a fonction

`takeWith` will be coded when this code naming convention will be clear in our mind (I will open a new issue for that):
```js
// todos.js
import { takeWith } from 'k-simple-state'
 
export const complete = takeWith(action, store) => {
  const { todos } = store.data 
  const todo = todos.get(action.payload)
  todos.set({ ...todos, completed: true })
}

// listeners.js
import { complete } from './todos' 

export default [
  // here it seems odd to me to call a fonction 'complete' passing an action type :)
  complete('@@ui/CLICKED_COMPLETE'),
]
```
